server.port=5000
server.host=localhost

# Multiple hosts and ports
server.open.host.1=localhost
server.open.port.1=5001

server.open.host.2=localhost
server.open.port.2=5002

server.open.host.3=localhost
server.open.port.3=5003
