spring.application.name=microjvm-node

microjvm.node.id=${NODE_ID:node-local}
microjvm.node.peer-host=${PEER_HOST:}
microjvm.node.peer-port=${PEER_PORT:0}
microjvm.spike.enabled=${SPIKE_ENABLED:false}

grpc.server.port=${GRPC_PORT:9090}
grpc.server.address=0.0.0.0
